# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

run:
  # default: '1m'
  timeout: '5m'

  # default: []
  build-tags:
    - 'all'

  # default: ''
  modules-download-mode: 'readonly'

  # default: false
  allow-parallel-runners: true

linters:
  enable:
    - 'asasalint'
    - 'asciicheck'
    - 'bidichk'
    - 'bodyclose'
    - 'containedctx'
    # - 'copyloopvar' TODO: enable after everything is upgraded to Go 1.22
    - 'depguard'
    - 'dupword'
    - 'durationcheck'
    - 'errcheck'
    - 'errchkjson'
    - 'errname'
    - 'errorlint'
    - 'exhaustive'
    - 'forcetypeassert'
    - 'gci'
    - 'gocheckcompilerdirectives'
    - 'godot'
    - 'gofmt'
    - 'gofumpt'
    - 'goheader'
    - 'goimports'
    - 'goprintffuncname'
    - 'gosec'
    - 'gosimple'
    - 'govet'
    - 'importas'
    - 'ineffassign'
    - 'loggercheck'
    - 'makezero'
    - 'mirror'
    - 'misspell'
    - 'nilerr'
    - 'noctx'
    - 'nolintlint'
    - 'nosprintfhostport'
    - 'paralleltest'
    - 'prealloc'
    - 'predeclared'
    - 'protogetter'
    - 'rowserrcheck'
    - 'sloglint'
    - 'spancheck'
    - 'sqlclosecheck'
    - 'staticcheck'
    - 'stylecheck'
    - 'tenv'
    - 'thelper'
    - 'typecheck'
    - 'unconvert'
    - 'unused'
    - 'wastedassign'
    - 'whitespace'
    - 'wrapcheck'

issues:
  # default: []
  exclude:
    - '^G102:' # gosec: we have to bind to all ifaces in Cloud Run services
    - '^G115:' # gosec: there's no way to actually satisfy this linter

  # default: []
  exclude-rules:
    # Exclude test files from certain linters
    - path: '_test.go'
      linters:
        - 'wrapcheck'

  # default: []
  exclude-dirs:
    - 'internal/pb'
    - 'third_party'

  # default: true
  exclude-dirs-use-default: false

  # default: 50
  max-issues-per-linter: 0

  # default: 3
  max-same-issues: 0

linters-settings:
  depguard:
    rules:
      main:
        files:
          - '$all'
        deny:
          - pkg: 'github.com/auth0/go-jwt-middleware'
            desc: 'the approved jwx library is github.com/lestrrat-go/jwx/v2'
          - pkg: 'github.com/gin-contrib/*'
            desc: 'third-party web frameworks are not approved, use net/http'
          - pkg: 'github.com/gin-gonic/contrib'
            desc: 'third-party web frameworks are not approved, use net/http'
          - pkg: 'github.com/gin-gonic/gin'
            desc: 'third-party web frameworks are not approved, use net/http'
          - pkg: 'github.com/golang-jwt/jwe'
            desc: 'the approved jwx library is github.com/lestrrat-go/jwx/v2'
          - pkg: 'github.com/golang-jwt/jwt'
            desc: 'the approved jwx library is github.com/lestrrat-go/jwx/v2'
          - pkg: 'github.com/stretchr/testify'
            desc: 'use the standard library for tests'

  gci:
    sections:
      - 'standard'
      - 'default'
      - 'prefix(github.com/abcxyz)'
      - 'blank'
      - 'dot'

    skip-generated: true
    custom-order: true

  gofumpt:
    # default: false
    extra-rules: true

  goheader:
    values:
      regexp:
        YEAR_AUTHOR: '\d{4} .*'
        INDENTATION: '[\t\f]+|[ ]{2,}'
    # default: ""
    template: |-
      Copyright {{ YEAR_AUTHOR }}

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

      {{ INDENTATION }}http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.

  sloglint:
    # default: false
    context: 'all'
    # default: false
    static-msg: false
    # default: '' (snake, kebab, camel, pascal)
    key-naming-case: 'snake'
    # default: false
    args-on-sep-lines: true

  wrapcheck:
    ignoreSigRegexps:
      - '\.ErrorOrNil\('
      - '\.StartGRPC\('
      - '\.StartHTTP\('
      - '\.StartHTTPHandler\('
      - 'retry\.RetryableError\('
      - 'status\.Error\('

severity:
  # default: ''
  default-severity: 'error'
