# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

run:
  # default: '1m'
  timeout: '5m'

  # default: []
  build-tags:
    - 'all'

  # default: []
  skip-dirs:
    - 'internal/pb'
    - 'third_party'

  # default: true
  skip-dirs-use-default: false

  # default: ''
  modules-download-mode: 'readonly'

  # default: false
  allow-parallel-runners: true

linters:
  enable:
    - 'asasalint'
    - 'asciicheck'
    - 'bidichk'
    - 'bodyclose'
    - 'containedctx'
    - 'depguard'
    - 'dupword'
    - 'durationcheck'
    - 'errcheck'
    - 'errchkjson'
    - 'errname'
    - 'errorlint'
    - 'execinquery'
    - 'exhaustive'
    - 'exportloopref'
    - 'forcetypeassert'
    - 'gocheckcompilerdirectives'
    - 'godot'
    - 'gofmt'
    - 'gofumpt'
    - 'goheader'
    - 'goimports'
    - 'goprintffuncname'
    - 'gosec'
    - 'gosimple'
    - 'govet'
    - 'importas'
    - 'ineffassign'
    # - 'ireturn' # does not handle generics yet: https://github.com/butuzov/ireturn/issues/37
    - 'loggercheck'
    - 'makezero'
    - 'misspell'
    - 'noctx'
    - 'nolintlint'
    - 'nosprintfhostport'
    - 'paralleltest'
    - 'prealloc'
    - 'predeclared'
    - 'rowserrcheck'
    - 'sqlclosecheck'
    - 'staticcheck'
    - 'stylecheck'
    - 'tenv'
    - 'thelper'
    - 'typecheck'
    - 'unconvert'
    - 'unused'
    - 'wastedassign'
    - 'whitespace'
    - 'wrapcheck'

issues:
  # default: []
  exclude:
    - '^G102:' # gosec: we have to bind to all ifaces in Cloud Run services

  # default: []
  exclude-rules:
    # Exclude test files from certain linters
    - path: '_test.go'
      linters:
        - 'wrapcheck'

  # default: 50
  max-issues-per-linter: 0

  # default: 3
  max-same-issues: 0

linters-settings:
  depguard:
    list-type: 'denylist'
    packages-with-error-message:
      - 'github.com/auth0/go-jwt-middleware': 'the approved jwx library is github.com/lestrrat-go/jwx/v2'
      - 'github.com/gin-contrib/*': 'third-party web frameworks are not approved, use net/http'
      - 'github.com/gin-gonic/contrib': 'third-party web frameworks are not approved, use net/http'
      - 'github.com/gin-gonic/gin': 'third-party web frameworks are not approved, use net/http'
      - 'github.com/golang-jwt/jwe': 'the approved jwx library is github.com/lestrrat-go/jwx/v2'
      - 'github.com/golang-jwt/jwt': 'the approved jwx library is github.com/lestrrat-go/jwx/v2'

  gofumpt:
    # default: false
    extra-rules: true

  goheader:
    values:
      regexp:
        YEAR_AUTHOR: '\d{4} .*'
        INDENTATION: '[\t\f]+|[ ]{2,}'
    # default: ""
    template: |-
      Copyright {{ YEAR_AUTHOR }}

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

      {{ INDENTATION }}http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.

  wrapcheck:
    ignoreSigRegexps:
      - '\.ErrorOrNil\('
      - '\.StartGRPC\('
      - '\.StartHTTP\('
      - '\.StartHTTPHandler\('
      - 'retry\.RetryableError\('
      - 'status\.Error\('

severity:
  # default: ''
  default-severity: 'error'
