name: 'multi-approvers action'
description: 'Requires multiple internal approvals for external PRs.'

inputs:
  token:
    description: 'GitHub token with at least members:read, pull_requests:read, and actions:write permissions.'
    required: true
    type: 'string'
  team:
    description: "Team slug. The team's organization must be in the repository's organization. Example: feature-team"
    required: true
    type: 'string'

runs:
  using: 'node20'
  main: 'dist/main/index.js'
