# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'terraform-linter action'
description: 'Lint terraform against the abcxyz style guide.'
inputs:
  directory:
    description: 'Directory with terraform files to lint'
    default: '.'

runs:
  using: 'composite'
  steps:
    - id: 'checkout-pkg'
      uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4
      with:
        repository: 'abcxyz/pkg'
        path: 'abcxyz-pkg'

    - id: 'setup-go'
      uses: 'actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34' # ratchet:actions/setup-go@v5
      with:
        go-version: '1.22'

    - id: 'run-linter'
      shell: 'bash'
      working-directory: 'abcxyz-pkg'
      run: |-
        go run ./cmd/terraform-linter ${GITHUB_WORKSPACE}/${{inputs.directory}}
