name: Check PR Description

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-description:
    runs-on: ubuntu-latest
    steps:
      # Step to check if the pull request description is empty
      - name: Check PR Description Not Empty
        run: |
          if [[ -z "${{ github.event.pull_request.body }}" ]]; then
            echo "Error: Pull request description cannot be empty."
            exit 1
          else
            echo "Pull request description is not empty."
            exit 0
          fi
