name: 'ci-docker-test'

on:
  pull_request:
    paths:
      - '.github/workflows/ci-docker-test.dockerfile'
      - '.github/workflows/ci-docker-test.yml'
      - '.github/workflows/maybe-build-docker.yml'

permissions:
  contents: 'read' # For checking out repository code.
  packages: 'write' # For pushing/pulling from github docker registry.

jobs:
  # First we check if we need to re-build the docker image.
  # If the hash of the dockerfile has changed then we rebuild and push to
  # github packages (and optionally GCP Artifact registry).
  maybe-create-ci-image:
    uses: './.github/workflows/maybe-build-docker.yml'
    with:
      dockerfile: '.github/workflows/ci-docker-test.dockerfile'
      github_image_name: 'ghcr.io/${{ github.repository }}/ci-docker-test'

  # Then we run using the latest docker image and build all artifacts in that
  # container.
  ci-on-docker-image:
    needs:
      - 'maybe-create-ci-image'
    runs-on: 'ubuntu-latest'
    container:
      image: 'ghcr.io/${{ github.repository }}/ci-docker-test:${{ needs.maybe-create-ci-image.outputs.docker_tag }}'
      credentials:
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - name: 'Check installs'
        shell: 'bash'
        run: |
          which gcloud
