name: 'cleanup'

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

  # tmp:
  push:

jobs:
  remove-old-workflows:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Mint token'
        id: 'mint-token'
        uses: 'abcxyz/github-token-minter/.github/actions/mint-token@main' # ratchet:exclude
        with:
          wif_provider: '${{ vars.TOKEN_MINTER_WIF_PROVIDER }}'
          wif_service_account: '${{ vars.TOKEN_MINTER_WIF_SERVICE_ACCOUNT }}'
          service_audience: '${{ vars.TOKEN_MINTER_SERVICE_AUDIENCE }}'
          service_url: '${{ vars.TOKEN_MINTER_SERVICE_URL }}'
          requested_permissions: |-
            {
              "repositories": ["*"],
              "permissions": {
                "workflows": "write"
              }
            }

      - name: 'Remove old workflows'
        uses: 'actions/github-script@v7'
        with:
          github-token: '${{ steps.mint-token.outputs.token }}'
          script: |-
            const repos = await github.paginate(github.rest.apps.listReposAccessibleToInstallation, {
              per_page: 100,
            });

            console.log({repos})
