name: 'go-lint'

on:
  workflow_call:
    inputs:
      go_version:
        description: 'The version of Go to install and use.'
        type: 'string'
        required: true
      golangci_url:
        description: 'The URL to a golangci file. This is only used if no file is found in the local directory.'
        type: 'string'
        default: 'https://raw.githubusercontent.com/abcxyz/pkg/main/.golangci.yml'
      directory:
        description: 'Directory in which Go files reside.'
        type: 'string'
        default: '.'
      golangci_lint_version:
        description: 'Version of golangci linter to use'
        type: 'string'
        default: 'v1.52'

jobs:
  # modules checks if the go modules are all up-to-date. While rare with modern
  # versions of Go, it's possible to take a dependency on a package without
  # updating the module file.
  #
  # Do not change this job name. Job names are used as identifiers in status
  # checks, and changing this name will cause status checks to fail.
  modules:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b' # ratchet:actions/checkout@v3

      - name: 'Setup Go'
        uses: 'actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568' # ratchet:actions/setup-go@v3
        with:
          go-version: '${{ inputs.go_version }}'

      - name: 'Check modules'
        shell: 'bash'
        working-directory: '${{ inputs.directory }}'
        run: |-
          for d in $(find . -name go.mod); do
            (cd $(dirname $d) && go mod tidy)
          done
          if [ -n "$(git status -s -uall)" ]; then
            echo "::error title=Go module changes::Detected go module changes"
            git -c color.ui=always diff
            exit 1
          fi

  # golangci runs golangci-lint. If a .golangci.yml or .golangci.yaml file
  # exists at the root of the repository, it uses those custom settings. If no
  # such file exists, it uses a selection of sane defaults.
  #
  # Do not change this job name. Job names are used as identifiers in status
  # checks, and changing this name will cause status checks to fail.
  golangci:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b' # ratchet:actions/checkout@v3

      - name: 'Setup Go'
        uses: 'actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568' # ratchet:actions/setup-go@v3
        with:
          go-version: '${{ inputs.go_version }}'

      - name: 'Lint (download default configuration)'
        id: 'load-default-config'
        if: ${{ hashFiles('.golangci.yml', '.golangci.yaml') == '' }}
        run: |-
          # Create a unique output file outside of the checkout.
          GOLANGCI_YML="${RUNNER_TEMP}/${GITHUB_SHA:0:7}.golangci.yml"

          # Download the file, passing in authentication to get a higher rate
          # limit: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions
          curl "${{ inputs.golangci_url }}" \
            --silent \
            --fail \
            --location \
            --header "Authorization: Token ${{ github.token }}" \
            --output "${GOLANGCI_YML}"

          # Save the result to an output.
          echo "::notice::Wrote configuration file to ${GOLANGCI_YML}"
          echo "output-file=${GOLANGCI_YML}" >> "${GITHUB_OUTPUT}"

      - name: 'Lint (default configuration)'
        if: ${{ hashFiles('.golangci.yml', '.golangci.yaml') == '' }}
        uses: 'golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1' # ratchet:golangci/golangci-lint-action@v3
        with:
          args: |-
            --config "${{ steps.load-default-config.outputs.output-file }}"
          version: '${{ inputs.golangci_lint_version }}'
          skip-cache: true
          working-directory: '${{ inputs.directory }}'

      - name: 'Lint (custom configuration)'
        if: ${{ hashFiles('.golangci.yml', '.golangci.yaml') != '' }}
        uses: 'golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1' # ratchet:golangci/golangci-lint-action@v3
        with:
          version: '${{ inputs.golangci_lint_version }}'
          skip-cache: true
          working-directory: '${{ inputs.directory }}'
