# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'load-workflow-variables-test'

on:
  pull_request:
    paths:
      - '.github/actions/load-workflow-variables/**'
      - '.github/workflows/load-workflow-variables-test.yml'

jobs:
  success:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - name: 'Load Env Vars'
        uses: './.github/actions/load-workflow-variables' # ratchet:exclude
        with:
          working_directory: 'terraform/org'
          filepath: '.github/actions/load-workflow-variables/test.env.yml'
          fail_on_missing: true

      - name: 'Load Env Vars'
        uses: './.github/actions/load-workflow-variables' # ratchet:exclude
        with:
          working_directory: 'terraform/resources/project-a/production'
          filepath: '.github/actions/load-workflow-variables/test.env.yml'
          fail_on_missing: true

      - name: 'Load Env Vars'
        uses: './.github/actions/load-workflow-variables' # ratchet:exclude
        with:
          working_directory: 'terraform/resources/project-b/development'
          filepath: '.github/actions/load-workflow-variables/test.env.yml'
          fail_on_missing: true

      - name: 'Test'
        shell: 'bash'
        run: |-
          GOT="${ORG_OVERRIDE_VALUE}"
          WANT="terraform/org"
          if [[ "${GOT}" != "${WANT}" ]]; then
            echo "ORG_OVERRIDE_VALUE - got ${GOT} want ${WANT}"
            FAILURES="true"
          fi

          GOT="${PROJECT_A_OVERRIDE_VALUE}"
          WANT="project-a/all"
          if [[ "${GOT}" != "${WANT}" ]]; then
            echo "PROJECT_A_OVERRIDE_VALUE - got ${GOT} want ${WANT}"
            FAILURES="true"
          fi

          GOT="${PROJECT_B_OVERRIDE_VALUE}"
          WANT="project-b/development"
          if [[ "${GOT}" != "${WANT}" ]]; then
            echo "PROJECT_B_OVERRIDE_VALUE - got ${GOT} want ${WANT}"
            FAILURES="true"
          fi

          GOT="${ALL_VALUE}"
          WANT="project-b/development"
          if [[ "${GOT}" != "${WANT}" ]]; then
            echo "ALL_VALUE - got ${GOT} want ${WANT}"
            FAILURES="true"
          fi

          if [[ ! -z "${FAILURES}" ]]; then
            exit 1
          fi

  list:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - name: 'Load Env Vars'
        uses: './.github/actions/load-workflow-variables' # ratchet:exclude
        with:
          working_directory: 'terraform/deployments'
          filepath: '.github/actions/load-workflow-variables/test.env.yml'
          fail_on_missing: true

      - name: 'Refresh Test Value'
        shell: 'bash'
        run: |-
          GOT="${LIST_OVERRIDE_VALUE}"
          WANT="list/value"
          if [[ "${GOT}" != "${WANT}" ]]; then
            echo "LIST_OVERRIDE_VALUE - got ${GOT} want ${WANT}"
            exit 1
          fi

          echo "LIST_OVERRIDE_VALUE=wrong/value" >> $GITHUB_ENV

      - name: 'Load Env Vars'
        uses: './.github/actions/load-workflow-variables' # ratchet:exclude
        with:
          working_directory: 'terraform/experimental'
          filepath: '.github/actions/load-workflow-variables/test.env.yml'
          fail_on_missing: true

      - name: 'Test'
        shell: 'bash'
        run: |-
          GOT="${LIST_OVERRIDE_VALUE}"
          WANT="list/value"
          if [[ "${GOT}" != "${WANT}" ]]; then
            echo "LIST_OVERRIDE_VALUE - got ${GOT} want ${WANT}"
            exit 1
          fi

  missing_fail:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - name: 'Load Env Vars'
        id: 'load-env-vars'
        uses: './.github/actions/load-workflow-variables' # ratchet:exclude
        continue-on-error: true
        with:
          working_directory: 'terraform/project-c'
          filepath: '.github/actions/load-workflow-variables/test.env.yml'
          fail_on_missing: true

      - name: 'Expect Failure'
        if: |-
          steps.load-env-vars.outcome != 'failure'
        shell: 'bash'
        run: |-
          echo "Expected previous step to fail"
          exit 1

  missing_continue:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - name: 'Load Env Vars'
        id: 'load-env-vars'
        uses: './.github/actions/load-workflow-variables' # ratchet:exclude
        with:
          working_directory: 'terraform/project-c'
          filepath: '.github/actions/load-workflow-variables/test.env.yml'
          fail_on_missing: false
