name: 'multi-approvers'

on:
  workflow_call:
    inputs:
      # Path to a JSON file containing the members of the org.
      # See the README for more.
      org-members-path:
        required: true
        type: 'string'

permissions:
  actions: 'write'
  contents: 'read'
  pull-requests: 'read'

jobs:
  multi-approvers:
    if: |-
      contains(fromJSON('["pull_request", "pull_request_review"]'), github.event_name)
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b' # ratchet:actions/checkout@v4

      - name: 'Check approver requirements'
        uses: 'actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea' # ratchet:actions/github-script@v7
        with:
          retries: 3
          script: |-
            const orgMembersPath = '${{ inputs.org-members-path }}';
            // Warning: this should not be quoted, otherwise comparisons will not work in JS.
            const prNumber = ${{ github.event.pull_request.number }}
            const repoName = '${{ github.event.repository.name }}'
            const repoOwner = '${{ github.event.repository.owner.login }}'
            const {onPullRequest} = require('./.github/workflows/multi-approvers.js');
            await onPullRequest({
              orgMembersPath,
              prNumber,
              repoName,
              repoOwner,
              github,
              core,
            });

      - name: 'Re-run approver checks'
        if: |-
          github.event_name == 'pull_request_review'
        uses: 'actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea' # ratchet:actions/github-script@v7
        with:
          retries: 3
          script: |-
            const branch = '${{ github.event.pull_request.head.ref }}'
            // Warning: this should not be quoted, otherwise comparisons will not work in JS.
            const prNumber = ${{ github.event.pull_request.number }}
            const repoName = '${{ github.event.repository.name }}'
            const repoOwner = '${{ github.event.repository.owner.login }}'
            const workflowRef = '${{ github.workflow_ref }}';
            const {onPullRequestReview} = require('./.github/workflows/multi-approvers.js');
            await onPullRequestReview({
              branch,
              prNumber,
              repoName,
              repoOwner,
              workflowRef,
              github,
              core,
            });
