# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'setup-binary-test'

on:
  pull_request:
    paths:
      - '.github/actions/setup-binary/**'
jobs:
  setup-binary-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          - 'ubuntu-20.04'
          - 'windows-latest'
          - 'windows-2019'
          - 'macos-latest'
          - 'macos-11'
        include:
          - os: 'ubuntu-latest'
            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_linux_amd64.tar.gz'

          - os: 'ubuntu-20.04'
            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_linux_amd64.tar.gz'

          - os: 'windows-latest'
            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_windows_amd64.zip'

          - os: 'windows-2019'
            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_windows_amd64.zip'

          - os: 'macos-latest'
            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_darwin_amd64.tar.gz'

          - os: 'macos-11'
            download_url: 'https://github.com/abcxyz/abc/releases/download/v0.0.1-alpha4/abc_0.0.1-alpha4_darwin_amd64.tar.gz'

    runs-on: '${{ matrix.os }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3

      - name: 'Path'
        id: 'path'
        shell: 'bash'
        run: |
          echo "path=${HOME}/.abc" >> $GITHUB_OUTPUT

      - name: 'Setup binary (save cache)'
        uses: './.github/actions/setup-binary' # ratchet:exclude
        with:
          install_path: '${{ steps.path.outputs.path }}'
          download_url: '${{ matrix.download_url }}'
          cache_key: '${{ runner.name }}_abc_${{ github.sha }}'

      - name: 'Setup binary (restore cache)'
        uses: './.github/actions/setup-binary' # ratchet:exclude
        with:
          install_path: '${{ steps.path.outputs.path }}'
          download_url: '${{ matrix.download_url }}'
          cache_key: '${{ runner.name }}_abc_${{ github.sha }}'

      - name: 'Add binary to path'
        shell: 'bash'
        env:
          BINARY_PATH: '${{ steps.path.outputs.path }}'
        run: |-
          echo "${BINARY_PATH}" >> $GITHUB_PATH

      - name: 'Test'
        shell: 'bash'
        run: |
          GOT=$(abc -version 2>&1) # abcxyz/pkg/cli writes help to stderr
          WANT="abc 0.0.1-alpha4"

          if [[ "${GOT}" != "${WANT}"* ]]; then
            echo "::error ::Expected ${GOT} to be ${WANT}"
            exit 1
          fi
