# Copyright 2023 The Authors (see AUTHORS file)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'yaml-lint'

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The GitHub runner on which to execute. This must be a valid JSON but can represent a string, array of strings, or object.'
        type: 'string'
        default: '"ubuntu-latest"'
      yamllint_url:
        description: 'The URL to a yamllint config file. This is only used if no file is found in the local directory.'
        type: 'string'
        default: 'https://raw.githubusercontent.com/abcxyz/pkg/main/.yamllint.yml'
      yamllint_version:
        description: 'Version of yamllint linter to use'
        type: 'string'
        default: '1.35.1'
      target:
        description: 'File or directory containing YAML files to lint.'
        type: 'string'
        default: '.'

jobs:
  # yamllint runs yamllint. If a .yamllint.yml or .yamllint.yaml file exists at
  # the root of the repository, it uses those custom settings. If no such file
  # exists, it uses a selection of sane defaults.
  #
  # Do not change this job name. Job names are used as identifiers in status
  # checks, and changing this name will cause status checks to fail.
  yamllint:
    runs-on: ${{ fromJSON(inputs.runs-on) }} # yamllint disable-line
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - name: 'Lint Yaml'
        uses: 'abcxyz/actions/.github/actions/lint-yaml@main' # ratchet:exclude
        with:
          yamllint_url: '${{ inputs.yamllint_url }}'
          yamllint_version: '${{ inputs.yamllint_version }}'
          target: '${{ inputs.target }}'
